// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: DouYinHeader.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from DouYinHeader.proto</summary>
public static partial class DouYinHeaderReflection {

  #region Descriptor
  /// <summary>File descriptor for DouYinHeader.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static DouYinHeaderReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChJEb3VZaW5IZWFkZXIucHJvdG8iqgEKCVB1c2hGcmFtZRINCgVzZXFpZBgB",
          "IAEoAxINCgVsb2dpZBgCIAEoCRIPCgdzZXJ2aWNlGAMgASgDEg4KBm1ldGhv",
          "ZBgEIAEoAxIfCgpoZWFkZXJMaXN0GAUgAygLMgsuUHVzaEhlYWRlchIXCg9w",
          "YXlsb2FkRW5jb2RpbmcYBiABKAkSEwoLcGF5bG9hZFR5cGUYByABKAkSDwoH",
          "cGF5bG9hZBgIIAEoDCIoCgpQdXNoSGVhZGVyEgsKA2tleRgBIAEoAxINCgV2",
          "YWx1ZRgCIAEoCSLfAgoIUmVzcG9uc2USHgoMbWVzc2FnZXNMaXN0GAEgAygL",
          "MgguTWVzc2FnZRIOCgZjdXJzb3IYAiABKAkSFQoNZmV0Y2hJbnRlcnZhbBgD",
          "IAEoAxILCgNub3cYBCABKAMSEwoLaW50ZXJuYWxFeHQYBSABKAkSEQoJZmV0",
          "Y2hUeXBlGAYgASgDEjUKDnJvdXRlUGFyYW1zTWFwGAcgAygLMh0uUmVzcG9u",
          "c2UuUm91dGVQYXJhbXNNYXBFbnRyeRIZChFoZWFydGJlYXREdXJhdGlvbhgI",
          "IAEoCRIPCgduZWVkQWNrGAkgASgIEhIKCnB1c2hTZXJ2ZXIYCiABKAkSEgoK",
          "bGl2ZUN1cnNvchgLIAEoCRIVCg1oaXN0b3J5Tm9Nb3JlGAwgASgIGjUKE1Jv",
          "dXRlUGFyYW1zTWFwRW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgJ",
          "OgI4ASKKAgoHTWVzc2FnZRIOCgZtZXRob2QYASABKAkSDwoHcGF5bG9hZBgC",
          "IAEoDBINCgVtc2dJZBgDIAEoAxIPCgdtc2dUeXBlGAQgASgDEg4KBm9mZnNl",
          "dBgFIAEoCRIVCg1uZWVkV3Jkc1N0b3JlGAYgASgIEhMKC3dyZHNWZXJzaW9u",
          "GAcgASgJEhIKCndyZHNTdWJLZXkYCCABKAkSNgoPbWVzc2FnZUV4dHJhTWFw",
          "GAkgAygLMh0uTWVzc2FnZS5NZXNzYWdlRXh0cmFNYXBFbnRyeRo2ChRNZXNz",
          "YWdlRXh0cmFNYXBFbnRyeRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAk6",
          "AjgBQh8KD2VudGl0eS5wcm90b2J1ZkIMRG91WWluSGVhZGVyYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::PushFrame), global::PushFrame.Parser, new[]{ "Seqid", "Logid", "Service", "Method", "HeaderList", "PayloadEncoding", "PayloadType", "Payload" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::PushHeader), global::PushHeader.Parser, new[]{ "Key", "Value" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::Response), global::Response.Parser, new[]{ "MessagesList", "Cursor", "FetchInterval", "Now", "InternalExt", "FetchType", "RouteParamsMap", "HeartbeatDuration", "NeedAck", "PushServer", "LiveCursor", "HistoryNoMore" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
          new pbr::GeneratedClrTypeInfo(typeof(global::Message), global::Message.Parser, new[]{ "Method", "Payload", "MsgId", "MsgType", "Offset", "NeedWrdsStore", "WrdsVersion", "WrdsSubKey", "MessageExtraMap" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, })
        }));
  }
  #endregion

}
#region Messages
public sealed partial class PushFrame : pb::IMessage<PushFrame>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<PushFrame> _parser = new pb::MessageParser<PushFrame>(() => new PushFrame());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<PushFrame> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DouYinHeaderReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PushFrame() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PushFrame(PushFrame other) : this() {
    seqid_ = other.seqid_;
    logid_ = other.logid_;
    service_ = other.service_;
    method_ = other.method_;
    headerList_ = other.headerList_.Clone();
    payloadEncoding_ = other.payloadEncoding_;
    payloadType_ = other.payloadType_;
    payload_ = other.payload_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PushFrame Clone() {
    return new PushFrame(this);
  }

  /// <summary>Field number for the "seqid" field.</summary>
  public const int SeqidFieldNumber = 1;
  private long seqid_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long Seqid {
    get { return seqid_; }
    set {
      seqid_ = value;
    }
  }

  /// <summary>Field number for the "logid" field.</summary>
  public const int LogidFieldNumber = 2;
  private string logid_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Logid {
    get { return logid_; }
    set {
      logid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "service" field.</summary>
  public const int ServiceFieldNumber = 3;
  private long service_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long Service {
    get { return service_; }
    set {
      service_ = value;
    }
  }

  /// <summary>Field number for the "method" field.</summary>
  public const int MethodFieldNumber = 4;
  private long method_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long Method {
    get { return method_; }
    set {
      method_ = value;
    }
  }

  /// <summary>Field number for the "headerList" field.</summary>
  public const int HeaderListFieldNumber = 5;
  private static readonly pb::FieldCodec<global::PushHeader> _repeated_headerList_codec
      = pb::FieldCodec.ForMessage(42, global::PushHeader.Parser);
  private readonly pbc::RepeatedField<global::PushHeader> headerList_ = new pbc::RepeatedField<global::PushHeader>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::PushHeader> HeaderList {
    get { return headerList_; }
  }

  /// <summary>Field number for the "payloadEncoding" field.</summary>
  public const int PayloadEncodingFieldNumber = 6;
  private string payloadEncoding_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string PayloadEncoding {
    get { return payloadEncoding_; }
    set {
      payloadEncoding_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "payloadType" field.</summary>
  public const int PayloadTypeFieldNumber = 7;
  private string payloadType_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string PayloadType {
    get { return payloadType_; }
    set {
      payloadType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "payload" field.</summary>
  public const int PayloadFieldNumber = 8;
  private pb::ByteString payload_ = pb::ByteString.Empty;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pb::ByteString Payload {
    get { return payload_; }
    set {
      payload_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as PushFrame);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(PushFrame other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Seqid != other.Seqid) return false;
    if (Logid != other.Logid) return false;
    if (Service != other.Service) return false;
    if (Method != other.Method) return false;
    if(!headerList_.Equals(other.headerList_)) return false;
    if (PayloadEncoding != other.PayloadEncoding) return false;
    if (PayloadType != other.PayloadType) return false;
    if (Payload != other.Payload) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Seqid != 0L) hash ^= Seqid.GetHashCode();
    if (Logid.Length != 0) hash ^= Logid.GetHashCode();
    if (Service != 0L) hash ^= Service.GetHashCode();
    if (Method != 0L) hash ^= Method.GetHashCode();
    hash ^= headerList_.GetHashCode();
    if (PayloadEncoding.Length != 0) hash ^= PayloadEncoding.GetHashCode();
    if (PayloadType.Length != 0) hash ^= PayloadType.GetHashCode();
    if (Payload.Length != 0) hash ^= Payload.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Seqid != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(Seqid);
    }
    if (Logid.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Logid);
    }
    if (Service != 0L) {
      output.WriteRawTag(24);
      output.WriteInt64(Service);
    }
    if (Method != 0L) {
      output.WriteRawTag(32);
      output.WriteInt64(Method);
    }
    headerList_.WriteTo(output, _repeated_headerList_codec);
    if (PayloadEncoding.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(PayloadEncoding);
    }
    if (PayloadType.Length != 0) {
      output.WriteRawTag(58);
      output.WriteString(PayloadType);
    }
    if (Payload.Length != 0) {
      output.WriteRawTag(66);
      output.WriteBytes(Payload);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Seqid != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(Seqid);
    }
    if (Logid.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Logid);
    }
    if (Service != 0L) {
      output.WriteRawTag(24);
      output.WriteInt64(Service);
    }
    if (Method != 0L) {
      output.WriteRawTag(32);
      output.WriteInt64(Method);
    }
    headerList_.WriteTo(ref output, _repeated_headerList_codec);
    if (PayloadEncoding.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(PayloadEncoding);
    }
    if (PayloadType.Length != 0) {
      output.WriteRawTag(58);
      output.WriteString(PayloadType);
    }
    if (Payload.Length != 0) {
      output.WriteRawTag(66);
      output.WriteBytes(Payload);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Seqid != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(Seqid);
    }
    if (Logid.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Logid);
    }
    if (Service != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(Service);
    }
    if (Method != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(Method);
    }
    size += headerList_.CalculateSize(_repeated_headerList_codec);
    if (PayloadEncoding.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(PayloadEncoding);
    }
    if (PayloadType.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(PayloadType);
    }
    if (Payload.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(Payload);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(PushFrame other) {
    if (other == null) {
      return;
    }
    if (other.Seqid != 0L) {
      Seqid = other.Seqid;
    }
    if (other.Logid.Length != 0) {
      Logid = other.Logid;
    }
    if (other.Service != 0L) {
      Service = other.Service;
    }
    if (other.Method != 0L) {
      Method = other.Method;
    }
    headerList_.Add(other.headerList_);
    if (other.PayloadEncoding.Length != 0) {
      PayloadEncoding = other.PayloadEncoding;
    }
    if (other.PayloadType.Length != 0) {
      PayloadType = other.PayloadType;
    }
    if (other.Payload.Length != 0) {
      Payload = other.Payload;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Seqid = input.ReadInt64();
          break;
        }
        case 18: {
          Logid = input.ReadString();
          break;
        }
        case 24: {
          Service = input.ReadInt64();
          break;
        }
        case 32: {
          Method = input.ReadInt64();
          break;
        }
        case 42: {
          headerList_.AddEntriesFrom(input, _repeated_headerList_codec);
          break;
        }
        case 50: {
          PayloadEncoding = input.ReadString();
          break;
        }
        case 58: {
          PayloadType = input.ReadString();
          break;
        }
        case 66: {
          Payload = input.ReadBytes();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Seqid = input.ReadInt64();
          break;
        }
        case 18: {
          Logid = input.ReadString();
          break;
        }
        case 24: {
          Service = input.ReadInt64();
          break;
        }
        case 32: {
          Method = input.ReadInt64();
          break;
        }
        case 42: {
          headerList_.AddEntriesFrom(ref input, _repeated_headerList_codec);
          break;
        }
        case 50: {
          PayloadEncoding = input.ReadString();
          break;
        }
        case 58: {
          PayloadType = input.ReadString();
          break;
        }
        case 66: {
          Payload = input.ReadBytes();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class PushHeader : pb::IMessage<PushHeader>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<PushHeader> _parser = new pb::MessageParser<PushHeader>(() => new PushHeader());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<PushHeader> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DouYinHeaderReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PushHeader() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PushHeader(PushHeader other) : this() {
    key_ = other.key_;
    value_ = other.value_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PushHeader Clone() {
    return new PushHeader(this);
  }

  /// <summary>Field number for the "key" field.</summary>
  public const int KeyFieldNumber = 1;
  private long key_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long Key {
    get { return key_; }
    set {
      key_ = value;
    }
  }

  /// <summary>Field number for the "value" field.</summary>
  public const int ValueFieldNumber = 2;
  private string value_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Value {
    get { return value_; }
    set {
      value_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as PushHeader);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(PushHeader other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Key != other.Key) return false;
    if (Value != other.Value) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Key != 0L) hash ^= Key.GetHashCode();
    if (Value.Length != 0) hash ^= Value.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Key != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(Key);
    }
    if (Value.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Value);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Key != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(Key);
    }
    if (Value.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Value);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Key != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(Key);
    }
    if (Value.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Value);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(PushHeader other) {
    if (other == null) {
      return;
    }
    if (other.Key != 0L) {
      Key = other.Key;
    }
    if (other.Value.Length != 0) {
      Value = other.Value;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Key = input.ReadInt64();
          break;
        }
        case 18: {
          Value = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Key = input.ReadInt64();
          break;
        }
        case 18: {
          Value = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class Response : pb::IMessage<Response>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Response> _parser = new pb::MessageParser<Response>(() => new Response());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<Response> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DouYinHeaderReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Response() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Response(Response other) : this() {
    messagesList_ = other.messagesList_.Clone();
    cursor_ = other.cursor_;
    fetchInterval_ = other.fetchInterval_;
    now_ = other.now_;
    internalExt_ = other.internalExt_;
    fetchType_ = other.fetchType_;
    routeParamsMap_ = other.routeParamsMap_.Clone();
    heartbeatDuration_ = other.heartbeatDuration_;
    needAck_ = other.needAck_;
    pushServer_ = other.pushServer_;
    liveCursor_ = other.liveCursor_;
    historyNoMore_ = other.historyNoMore_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Response Clone() {
    return new Response(this);
  }

  /// <summary>Field number for the "messagesList" field.</summary>
  public const int MessagesListFieldNumber = 1;
  private static readonly pb::FieldCodec<global::Message> _repeated_messagesList_codec
      = pb::FieldCodec.ForMessage(10, global::Message.Parser);
  private readonly pbc::RepeatedField<global::Message> messagesList_ = new pbc::RepeatedField<global::Message>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::Message> MessagesList {
    get { return messagesList_; }
  }

  /// <summary>Field number for the "cursor" field.</summary>
  public const int CursorFieldNumber = 2;
  private string cursor_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Cursor {
    get { return cursor_; }
    set {
      cursor_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "fetchInterval" field.</summary>
  public const int FetchIntervalFieldNumber = 3;
  private long fetchInterval_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long FetchInterval {
    get { return fetchInterval_; }
    set {
      fetchInterval_ = value;
    }
  }

  /// <summary>Field number for the "now" field.</summary>
  public const int NowFieldNumber = 4;
  private long now_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long Now {
    get { return now_; }
    set {
      now_ = value;
    }
  }

  /// <summary>Field number for the "internalExt" field.</summary>
  public const int InternalExtFieldNumber = 5;
  private string internalExt_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string InternalExt {
    get { return internalExt_; }
    set {
      internalExt_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "fetchType" field.</summary>
  public const int FetchTypeFieldNumber = 6;
  private long fetchType_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long FetchType {
    get { return fetchType_; }
    set {
      fetchType_ = value;
    }
  }

  /// <summary>Field number for the "routeParamsMap" field.</summary>
  public const int RouteParamsMapFieldNumber = 7;
  private static readonly pbc::MapField<string, string>.Codec _map_routeParamsMap_codec
      = new pbc::MapField<string, string>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForString(18, ""), 58);
  private readonly pbc::MapField<string, string> routeParamsMap_ = new pbc::MapField<string, string>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::MapField<string, string> RouteParamsMap {
    get { return routeParamsMap_; }
  }

  /// <summary>Field number for the "heartbeatDuration" field.</summary>
  public const int HeartbeatDurationFieldNumber = 8;
  private string heartbeatDuration_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string HeartbeatDuration {
    get { return heartbeatDuration_; }
    set {
      heartbeatDuration_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "needAck" field.</summary>
  public const int NeedAckFieldNumber = 9;
  private bool needAck_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool NeedAck {
    get { return needAck_; }
    set {
      needAck_ = value;
    }
  }

  /// <summary>Field number for the "pushServer" field.</summary>
  public const int PushServerFieldNumber = 10;
  private string pushServer_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string PushServer {
    get { return pushServer_; }
    set {
      pushServer_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "liveCursor" field.</summary>
  public const int LiveCursorFieldNumber = 11;
  private string liveCursor_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string LiveCursor {
    get { return liveCursor_; }
    set {
      liveCursor_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "historyNoMore" field.</summary>
  public const int HistoryNoMoreFieldNumber = 12;
  private bool historyNoMore_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HistoryNoMore {
    get { return historyNoMore_; }
    set {
      historyNoMore_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as Response);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(Response other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if(!messagesList_.Equals(other.messagesList_)) return false;
    if (Cursor != other.Cursor) return false;
    if (FetchInterval != other.FetchInterval) return false;
    if (Now != other.Now) return false;
    if (InternalExt != other.InternalExt) return false;
    if (FetchType != other.FetchType) return false;
    if (!RouteParamsMap.Equals(other.RouteParamsMap)) return false;
    if (HeartbeatDuration != other.HeartbeatDuration) return false;
    if (NeedAck != other.NeedAck) return false;
    if (PushServer != other.PushServer) return false;
    if (LiveCursor != other.LiveCursor) return false;
    if (HistoryNoMore != other.HistoryNoMore) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= messagesList_.GetHashCode();
    if (Cursor.Length != 0) hash ^= Cursor.GetHashCode();
    if (FetchInterval != 0L) hash ^= FetchInterval.GetHashCode();
    if (Now != 0L) hash ^= Now.GetHashCode();
    if (InternalExt.Length != 0) hash ^= InternalExt.GetHashCode();
    if (FetchType != 0L) hash ^= FetchType.GetHashCode();
    hash ^= RouteParamsMap.GetHashCode();
    if (HeartbeatDuration.Length != 0) hash ^= HeartbeatDuration.GetHashCode();
    if (NeedAck != false) hash ^= NeedAck.GetHashCode();
    if (PushServer.Length != 0) hash ^= PushServer.GetHashCode();
    if (LiveCursor.Length != 0) hash ^= LiveCursor.GetHashCode();
    if (HistoryNoMore != false) hash ^= HistoryNoMore.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    messagesList_.WriteTo(output, _repeated_messagesList_codec);
    if (Cursor.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Cursor);
    }
    if (FetchInterval != 0L) {
      output.WriteRawTag(24);
      output.WriteInt64(FetchInterval);
    }
    if (Now != 0L) {
      output.WriteRawTag(32);
      output.WriteInt64(Now);
    }
    if (InternalExt.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(InternalExt);
    }
    if (FetchType != 0L) {
      output.WriteRawTag(48);
      output.WriteInt64(FetchType);
    }
    routeParamsMap_.WriteTo(output, _map_routeParamsMap_codec);
    if (HeartbeatDuration.Length != 0) {
      output.WriteRawTag(66);
      output.WriteString(HeartbeatDuration);
    }
    if (NeedAck != false) {
      output.WriteRawTag(72);
      output.WriteBool(NeedAck);
    }
    if (PushServer.Length != 0) {
      output.WriteRawTag(82);
      output.WriteString(PushServer);
    }
    if (LiveCursor.Length != 0) {
      output.WriteRawTag(90);
      output.WriteString(LiveCursor);
    }
    if (HistoryNoMore != false) {
      output.WriteRawTag(96);
      output.WriteBool(HistoryNoMore);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    messagesList_.WriteTo(ref output, _repeated_messagesList_codec);
    if (Cursor.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Cursor);
    }
    if (FetchInterval != 0L) {
      output.WriteRawTag(24);
      output.WriteInt64(FetchInterval);
    }
    if (Now != 0L) {
      output.WriteRawTag(32);
      output.WriteInt64(Now);
    }
    if (InternalExt.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(InternalExt);
    }
    if (FetchType != 0L) {
      output.WriteRawTag(48);
      output.WriteInt64(FetchType);
    }
    routeParamsMap_.WriteTo(ref output, _map_routeParamsMap_codec);
    if (HeartbeatDuration.Length != 0) {
      output.WriteRawTag(66);
      output.WriteString(HeartbeatDuration);
    }
    if (NeedAck != false) {
      output.WriteRawTag(72);
      output.WriteBool(NeedAck);
    }
    if (PushServer.Length != 0) {
      output.WriteRawTag(82);
      output.WriteString(PushServer);
    }
    if (LiveCursor.Length != 0) {
      output.WriteRawTag(90);
      output.WriteString(LiveCursor);
    }
    if (HistoryNoMore != false) {
      output.WriteRawTag(96);
      output.WriteBool(HistoryNoMore);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    size += messagesList_.CalculateSize(_repeated_messagesList_codec);
    if (Cursor.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Cursor);
    }
    if (FetchInterval != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(FetchInterval);
    }
    if (Now != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(Now);
    }
    if (InternalExt.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(InternalExt);
    }
    if (FetchType != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(FetchType);
    }
    size += routeParamsMap_.CalculateSize(_map_routeParamsMap_codec);
    if (HeartbeatDuration.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(HeartbeatDuration);
    }
    if (NeedAck != false) {
      size += 1 + 1;
    }
    if (PushServer.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(PushServer);
    }
    if (LiveCursor.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(LiveCursor);
    }
    if (HistoryNoMore != false) {
      size += 1 + 1;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(Response other) {
    if (other == null) {
      return;
    }
    messagesList_.Add(other.messagesList_);
    if (other.Cursor.Length != 0) {
      Cursor = other.Cursor;
    }
    if (other.FetchInterval != 0L) {
      FetchInterval = other.FetchInterval;
    }
    if (other.Now != 0L) {
      Now = other.Now;
    }
    if (other.InternalExt.Length != 0) {
      InternalExt = other.InternalExt;
    }
    if (other.FetchType != 0L) {
      FetchType = other.FetchType;
    }
    routeParamsMap_.MergeFrom(other.routeParamsMap_);
    if (other.HeartbeatDuration.Length != 0) {
      HeartbeatDuration = other.HeartbeatDuration;
    }
    if (other.NeedAck != false) {
      NeedAck = other.NeedAck;
    }
    if (other.PushServer.Length != 0) {
      PushServer = other.PushServer;
    }
    if (other.LiveCursor.Length != 0) {
      LiveCursor = other.LiveCursor;
    }
    if (other.HistoryNoMore != false) {
      HistoryNoMore = other.HistoryNoMore;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          messagesList_.AddEntriesFrom(input, _repeated_messagesList_codec);
          break;
        }
        case 18: {
          Cursor = input.ReadString();
          break;
        }
        case 24: {
          FetchInterval = input.ReadInt64();
          break;
        }
        case 32: {
          Now = input.ReadInt64();
          break;
        }
        case 42: {
          InternalExt = input.ReadString();
          break;
        }
        case 48: {
          FetchType = input.ReadInt64();
          break;
        }
        case 58: {
          routeParamsMap_.AddEntriesFrom(input, _map_routeParamsMap_codec);
          break;
        }
        case 66: {
          HeartbeatDuration = input.ReadString();
          break;
        }
        case 72: {
          NeedAck = input.ReadBool();
          break;
        }
        case 82: {
          PushServer = input.ReadString();
          break;
        }
        case 90: {
          LiveCursor = input.ReadString();
          break;
        }
        case 96: {
          HistoryNoMore = input.ReadBool();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          messagesList_.AddEntriesFrom(ref input, _repeated_messagesList_codec);
          break;
        }
        case 18: {
          Cursor = input.ReadString();
          break;
        }
        case 24: {
          FetchInterval = input.ReadInt64();
          break;
        }
        case 32: {
          Now = input.ReadInt64();
          break;
        }
        case 42: {
          InternalExt = input.ReadString();
          break;
        }
        case 48: {
          FetchType = input.ReadInt64();
          break;
        }
        case 58: {
          routeParamsMap_.AddEntriesFrom(ref input, _map_routeParamsMap_codec);
          break;
        }
        case 66: {
          HeartbeatDuration = input.ReadString();
          break;
        }
        case 72: {
          NeedAck = input.ReadBool();
          break;
        }
        case 82: {
          PushServer = input.ReadString();
          break;
        }
        case 90: {
          LiveCursor = input.ReadString();
          break;
        }
        case 96: {
          HistoryNoMore = input.ReadBool();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class Message : pb::IMessage<Message>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Message> _parser = new pb::MessageParser<Message>(() => new Message());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<Message> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DouYinHeaderReflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Message() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Message(Message other) : this() {
    method_ = other.method_;
    payload_ = other.payload_;
    msgId_ = other.msgId_;
    msgType_ = other.msgType_;
    offset_ = other.offset_;
    needWrdsStore_ = other.needWrdsStore_;
    wrdsVersion_ = other.wrdsVersion_;
    wrdsSubKey_ = other.wrdsSubKey_;
    messageExtraMap_ = other.messageExtraMap_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Message Clone() {
    return new Message(this);
  }

  /// <summary>Field number for the "method" field.</summary>
  public const int MethodFieldNumber = 1;
  private string method_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Method {
    get { return method_; }
    set {
      method_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "payload" field.</summary>
  public const int PayloadFieldNumber = 2;
  private pb::ByteString payload_ = pb::ByteString.Empty;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pb::ByteString Payload {
    get { return payload_; }
    set {
      payload_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "msgId" field.</summary>
  public const int MsgIdFieldNumber = 3;
  private long msgId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long MsgId {
    get { return msgId_; }
    set {
      msgId_ = value;
    }
  }

  /// <summary>Field number for the "msgType" field.</summary>
  public const int MsgTypeFieldNumber = 4;
  private long msgType_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long MsgType {
    get { return msgType_; }
    set {
      msgType_ = value;
    }
  }

  /// <summary>Field number for the "offset" field.</summary>
  public const int OffsetFieldNumber = 5;
  private string offset_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Offset {
    get { return offset_; }
    set {
      offset_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "needWrdsStore" field.</summary>
  public const int NeedWrdsStoreFieldNumber = 6;
  private bool needWrdsStore_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool NeedWrdsStore {
    get { return needWrdsStore_; }
    set {
      needWrdsStore_ = value;
    }
  }

  /// <summary>Field number for the "wrdsVersion" field.</summary>
  public const int WrdsVersionFieldNumber = 7;
  private string wrdsVersion_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string WrdsVersion {
    get { return wrdsVersion_; }
    set {
      wrdsVersion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "wrdsSubKey" field.</summary>
  public const int WrdsSubKeyFieldNumber = 8;
  private string wrdsSubKey_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string WrdsSubKey {
    get { return wrdsSubKey_; }
    set {
      wrdsSubKey_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "messageExtraMap" field.</summary>
  public const int MessageExtraMapFieldNumber = 9;
  private static readonly pbc::MapField<string, string>.Codec _map_messageExtraMap_codec
      = new pbc::MapField<string, string>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForString(18, ""), 74);
  private readonly pbc::MapField<string, string> messageExtraMap_ = new pbc::MapField<string, string>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::MapField<string, string> MessageExtraMap {
    get { return messageExtraMap_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as Message);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(Message other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Method != other.Method) return false;
    if (Payload != other.Payload) return false;
    if (MsgId != other.MsgId) return false;
    if (MsgType != other.MsgType) return false;
    if (Offset != other.Offset) return false;
    if (NeedWrdsStore != other.NeedWrdsStore) return false;
    if (WrdsVersion != other.WrdsVersion) return false;
    if (WrdsSubKey != other.WrdsSubKey) return false;
    if (!MessageExtraMap.Equals(other.MessageExtraMap)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Method.Length != 0) hash ^= Method.GetHashCode();
    if (Payload.Length != 0) hash ^= Payload.GetHashCode();
    if (MsgId != 0L) hash ^= MsgId.GetHashCode();
    if (MsgType != 0L) hash ^= MsgType.GetHashCode();
    if (Offset.Length != 0) hash ^= Offset.GetHashCode();
    if (NeedWrdsStore != false) hash ^= NeedWrdsStore.GetHashCode();
    if (WrdsVersion.Length != 0) hash ^= WrdsVersion.GetHashCode();
    if (WrdsSubKey.Length != 0) hash ^= WrdsSubKey.GetHashCode();
    hash ^= MessageExtraMap.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Method.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Method);
    }
    if (Payload.Length != 0) {
      output.WriteRawTag(18);
      output.WriteBytes(Payload);
    }
    if (MsgId != 0L) {
      output.WriteRawTag(24);
      output.WriteInt64(MsgId);
    }
    if (MsgType != 0L) {
      output.WriteRawTag(32);
      output.WriteInt64(MsgType);
    }
    if (Offset.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(Offset);
    }
    if (NeedWrdsStore != false) {
      output.WriteRawTag(48);
      output.WriteBool(NeedWrdsStore);
    }
    if (WrdsVersion.Length != 0) {
      output.WriteRawTag(58);
      output.WriteString(WrdsVersion);
    }
    if (WrdsSubKey.Length != 0) {
      output.WriteRawTag(66);
      output.WriteString(WrdsSubKey);
    }
    messageExtraMap_.WriteTo(output, _map_messageExtraMap_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Method.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Method);
    }
    if (Payload.Length != 0) {
      output.WriteRawTag(18);
      output.WriteBytes(Payload);
    }
    if (MsgId != 0L) {
      output.WriteRawTag(24);
      output.WriteInt64(MsgId);
    }
    if (MsgType != 0L) {
      output.WriteRawTag(32);
      output.WriteInt64(MsgType);
    }
    if (Offset.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(Offset);
    }
    if (NeedWrdsStore != false) {
      output.WriteRawTag(48);
      output.WriteBool(NeedWrdsStore);
    }
    if (WrdsVersion.Length != 0) {
      output.WriteRawTag(58);
      output.WriteString(WrdsVersion);
    }
    if (WrdsSubKey.Length != 0) {
      output.WriteRawTag(66);
      output.WriteString(WrdsSubKey);
    }
    messageExtraMap_.WriteTo(ref output, _map_messageExtraMap_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Method.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Method);
    }
    if (Payload.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(Payload);
    }
    if (MsgId != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(MsgId);
    }
    if (MsgType != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(MsgType);
    }
    if (Offset.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Offset);
    }
    if (NeedWrdsStore != false) {
      size += 1 + 1;
    }
    if (WrdsVersion.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(WrdsVersion);
    }
    if (WrdsSubKey.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(WrdsSubKey);
    }
    size += messageExtraMap_.CalculateSize(_map_messageExtraMap_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(Message other) {
    if (other == null) {
      return;
    }
    if (other.Method.Length != 0) {
      Method = other.Method;
    }
    if (other.Payload.Length != 0) {
      Payload = other.Payload;
    }
    if (other.MsgId != 0L) {
      MsgId = other.MsgId;
    }
    if (other.MsgType != 0L) {
      MsgType = other.MsgType;
    }
    if (other.Offset.Length != 0) {
      Offset = other.Offset;
    }
    if (other.NeedWrdsStore != false) {
      NeedWrdsStore = other.NeedWrdsStore;
    }
    if (other.WrdsVersion.Length != 0) {
      WrdsVersion = other.WrdsVersion;
    }
    if (other.WrdsSubKey.Length != 0) {
      WrdsSubKey = other.WrdsSubKey;
    }
    messageExtraMap_.MergeFrom(other.messageExtraMap_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Method = input.ReadString();
          break;
        }
        case 18: {
          Payload = input.ReadBytes();
          break;
        }
        case 24: {
          MsgId = input.ReadInt64();
          break;
        }
        case 32: {
          MsgType = input.ReadInt64();
          break;
        }
        case 42: {
          Offset = input.ReadString();
          break;
        }
        case 48: {
          NeedWrdsStore = input.ReadBool();
          break;
        }
        case 58: {
          WrdsVersion = input.ReadString();
          break;
        }
        case 66: {
          WrdsSubKey = input.ReadString();
          break;
        }
        case 74: {
          messageExtraMap_.AddEntriesFrom(input, _map_messageExtraMap_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          Method = input.ReadString();
          break;
        }
        case 18: {
          Payload = input.ReadBytes();
          break;
        }
        case 24: {
          MsgId = input.ReadInt64();
          break;
        }
        case 32: {
          MsgType = input.ReadInt64();
          break;
        }
        case 42: {
          Offset = input.ReadString();
          break;
        }
        case 48: {
          NeedWrdsStore = input.ReadBool();
          break;
        }
        case 58: {
          WrdsVersion = input.ReadString();
          break;
        }
        case 66: {
          WrdsSubKey = input.ReadString();
          break;
        }
        case 74: {
          messageExtraMap_.AddEntriesFrom(ref input, _map_messageExtraMap_codec);
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
